# Generated by Django 4.1.6 on 2023-02-09 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='photo',
        ),
    ]
