# Generated by Django 4.1.6 on 2023-02-16 12:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0003_goods_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='photo',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='photos/%Y/%m/%d/', verbose_name='Фото'),
            preserve_default=False,
        ),
    ]
